/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  // But you can create a sidebar manually
  
  // mysideSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],

  /* 
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'installation',
        'configuration',
        'playground',
        'typescript-support',
      ],
    },
  */
  docs: [
    'intro',
    'marketplace',
    'nft',
    'DAO', 
    'gas-fee',
  ],
  marketplace: [
    {
      type: 'autogenerated',
      dirName: 'marketplace',
    },
  ],
  exchange: [
    {
      type: 'autogenerated',
      dirName: 'exchange',
    },
  ],
  nft: [
    {
      type: 'autogenerated',
      dirName: 'nft',
    },
  ],
  buha: [
    {
      type: 'autogenerated',
      dirName: 'buha',
    },
  ],
};

module.exports = sidebars;
